/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package NIMFinder;

import java.sql.Connection;

public class App {
    public static Connection connectgradlemysql()
    }

    public static void main(String[] args) {
      
        }
}
